apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-example
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: action-runner-demo/eks_ci
      labels:
        - self-hosted
      resources:
        limits:
          cpu: 300m
          memory: 500Mi